"""Primitive, renderer-independent dix capabilities."""

from .application import ApplicationComponent, ApplicationComponentError
from .composition import CompositionComponent, CompositionComponentError
from .contract import (
    ContractDefinition,
    ContractNotFound,
    ContractReference,
    ContractSpecError,
    inspect_contract_spec,
)
from .datamodel import (
    DatamodelComponent,
    DatamodelError,
    ModelDefinition,
    ModelIssue,
    ModelNotFound,
    ModelResult,
    RegisteredModel,
    RegisteredModelDescriptor,
)
from .element import (
    ElementBinding,
    ElementBindingError,
    ElementComponent,
    ElementError,
    ElementHandler,
    ElementIssue,
    ElementProcessor,
    ElementResult,
    ElementScope,
    ElementSpec,
    ElementTypeDescriptor,
    UnknownElementType,
)
from .function import (
    FunctionContract,
    FunctionParameterDescriptor,
    FunctionProjection,
    FunctionValueContract,
    derive_function_contract,
)
from .module.component import ModuleComponent, ModuleComponentError
from .norn import (
    MODEL_ELEMENT_TYPE,
    NornComponent,
    NornError,
    RegisteredStrand,
    StrandBinding,
    StrandDefinition,
    StrandDefinitionError,
    StrandDescriptor,
    StrandExecutionError,
    StrandInputError,
    StrandNotBound,
    StrandNotFound,
    StrandOutputError,
    StrandRegistrationError,
    StrandValueError,
    model_definition,
    model_element,
)
from .registry import (
    ComponentLifetime,
    ComponentProvider,
    ComponentRegistry,
    ComponentRegistryError,
    ComponentScope,
    create_core_component_registry,
)

__all__ = [
    "MODEL_ELEMENT_TYPE",
    "ApplicationComponent",
    "ApplicationComponentError",
    "ComponentLifetime",
    "ComponentProvider",
    "ComponentRegistry",
    "ComponentRegistryError",
    "ComponentScope",
    "CompositionComponent",
    "CompositionComponentError",
    "ContractDefinition",
    "ContractNotFound",
    "ContractReference",
    "ContractSpecError",
    "DatamodelComponent",
    "DatamodelError",
    "ElementBinding",
    "ElementBindingError",
    "ElementComponent",
    "ElementError",
    "ElementHandler",
    "ElementIssue",
    "ElementProcessor",
    "ElementResult",
    "ElementScope",
    "ElementSpec",
    "ElementTypeDescriptor",
    "FunctionContract",
    "FunctionParameterDescriptor",
    "FunctionProjection",
    "FunctionValueContract",
    "ModelDefinition",
    "ModelIssue",
    "ModelNotFound",
    "ModelResult",
    "ModuleComponent",
    "ModuleComponentError",
    "NornComponent",
    "NornError",
    "RegisteredModel",
    "RegisteredModelDescriptor",
    "RegisteredStrand",
    "StrandBinding",
    "StrandDefinition",
    "StrandDefinitionError",
    "StrandDescriptor",
    "StrandExecutionError",
    "StrandInputError",
    "StrandNotBound",
    "StrandNotFound",
    "StrandOutputError",
    "StrandRegistrationError",
    "StrandValueError",
    "UnknownElementType",
    "create_core_component_registry",
    "derive_function_contract",
    "inspect_contract_spec",
    "model_definition",
    "model_element",
]
