[launcher]
name = "dix-roba"
adapter = "python_cli"
application = "dix/roba/cli"
function = "main"

[[modules]]
id = "dix/state"
source = "../../modules/dix/state"

[[modules]]
id = "dix/cli"
source = "../../modules/dix/cli"

[[modules]]
id = "dix/roba"
source = "../../modules/dix/roba"
