from __future__ import annotations

from .models import LauncherDefinition


def render_launcher(definition: LauncherDefinition) -> str:
    """Render one deterministic Python CLI launcher from a normalized definition."""
    if definition.adapter != "python_cli":
        raise ValueError(f"unsupported launcher adapter: {definition.adapter}")
    modules = ",\n".join(
        f"    ({module.id!r}, {str(module.source)!r})," for module in definition.modules
    )
    return f'''# Generated by dix.bootstrap. Do not edit.
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

from dix.core import ApplicationComponent, ModuleComponent, create_core_component_registry
from dix.core.application import ApplicationInstanceSpec


LAUNCHER_NAME = {definition.name!r}
APPLICATION_ID = {definition.application!r}
FUNCTION_ID = {definition.function!r}
MODULES = (\n{modules}\n)


def _run(arguments: list[str]) -> int:
    registry = create_core_component_registry()
    module_component = registry.require("module", ModuleComponent)
    application_component = registry.require("application", ApplicationComponent)
    loaded_module_ids: list[str] = []
    application_created = False
    primary_error: BaseException | None = None
    instance_id = "entry"
    owner_scope_id = f"launcher:{{LAUNCHER_NAME}}"
    try:
        for module_id, source in MODULES:
            module_component.load_module(Path(source), module_id=module_id)
            loaded_module_ids.append(module_id)
        instance = application_component.create_instance(
            ApplicationInstanceSpec(
                id=instance_id,
                use=APPLICATION_ID,
                config={{}},
                config_base_dir=Path.cwd(),
            ),
            owner_scope_id=owner_scope_id,
        )
        application_created = True
        result = asyncio.run(instance.api.invoke(FUNCTION_ID, arguments))
        if type(result) is not int:
            raise TypeError("python_cli entry function must return an integer")
        return result
    except BaseException as exc:
        primary_error = exc
        raise
    finally:
        cleanup_errors: list[BaseException] = []
        if application_created:
            try:
                application_component.destroy_instance(owner_scope_id, instance_id)
            except BaseException as exc:
                cleanup_errors.append(exc)
        for module_id in reversed(loaded_module_ids):
            try:
                module_component.unload_module(module_id)
            except BaseException as exc:
                cleanup_errors.append(exc)
        if cleanup_errors:
            if primary_error is None:
                raise ExceptionGroup("launcher cleanup failed", cleanup_errors)
            for error in cleanup_errors:
                print(f"launcher cleanup failed: {{error}}", file=sys.stderr)


def main() -> int:
    return _run(sys.argv[1:])


if __name__ == "__main__":
    raise SystemExit(main())
'''
